package itson.sistemarestaurantepresentacion.modales;

import itson.sistemarestaurantedominio.dtos.IngredienteDTO;

/**
 *
 * @author pc
 */
public class ModalIngredientes extends javax.swing.JDialog {

    /**
     * Creates new form ModalIngredientes
     */
    public ModalIngredientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pnlBusquedaIngrediente.setSelectionMode(true);
        this.pnlBusquedaIngrediente.setModal(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBusquedaIngrediente = new itson.sistemarestaurantepresentacion.paneles.PnlBusquedaIngrediente();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBusquedaIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBusquedaIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public IngredienteDTO obtenerIngrediente() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        IngredienteDTO ingrediente = this.pnlBusquedaIngrediente.getIngredienteSeleccionado();
        if(ingrediente != null){
            return ingrediente;
        }
        return null;
    }

    /**
     * Método para cerrar el modal
     */
    public void cerrarModal(){
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.sistemarestaurantepresentacion.paneles.PnlBusquedaIngrediente pnlBusquedaIngrediente;
    // End of variables declaration//GEN-END:variables
}
