package itson.sistemarestaurantepresentacion.paneles;

import java.awt.Font;

import javax.swing.JOptionPane;

import itson.sistemarestaurantedominio.dtos.ComandaDTO;
import itson.sistemarestaurantedominio.dtos.MesaDTO;
import itson.sistemarestaurantenegocio.excepciones.NegocioException;
import itson.sistemarestaurantenegocio.factory.ObjetosNegocioFactory;
import itson.sistemarestaurantenegocio.interfaces.IMesasBO;
import itson.sistemarestaurantepresentacion.recursos.Formatos;

/**
 * Cla se que representa el panel de una comanda en la interfaz gráfica.
 * Contiene información sobre la mesa, estado, folio, fecha y hora de la
 * comanda.
 * 
 * @author pc
 */
public class PnlComanda extends javax.swing.JPanel {

    private ComandaDTO comanda;

    /**
     * Creates new form PnlComanda
     */
    public PnlComanda(ComandaDTO comanda) {
        this.comanda = comanda;
        initComponents();
        cargarComanda();
    }

    /**
     * Método para establecer los datos de la comanda en el panel.
     * @param comanda La comanda a mostrar.
     */
    private void cargarComanda(){
        try{
            lblFolio.setText("Folio: " + comanda.getFolio());
        IMesasBO mesasBO = ObjetosNegocioFactory.crearMesasBO(); 
        MesaDTO mesa = mesasBO.obtenerMesaPorId(comanda.getIdMesa());
        lblMesa.setText("Mesa " + mesa.getNumeroMesa());
        lblFecha.setText(Formatos.cargarFecha(comanda.getFechaHora()));
        lblHora.setText(Formatos.cargarHora(comanda.getFechaHora()));
        lblEstado.setText(comanda.getEstado().toString().substring(0, 1).toUpperCase()
                + comanda.getEstado().toString().substring(1).toLowerCase());
        } catch (NegocioException e){
            JOptionPane.showMessageDialog(this, "Error al cargar la comanda: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        lblMesa = new javax.swing.JLabel();
        pnlEstado = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        lblEstado = new javax.swing.JLabel();
        lblFolio = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        btnVerComanda = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        lblHora1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(37, 40, 54));

        roundedPanel1.setBackground(new java.awt.Color(40, 42, 53));
        roundedPanel1.setRoundBottomLeft(50);
        roundedPanel1.setRoundBottomRight(50);
        roundedPanel1.setRoundTopLeft(50);
        roundedPanel1.setRoundTopRight(50);

        lblMesa.setFont(new Font("Poppins", Font.BOLD, 22));
        lblMesa.setForeground(new java.awt.Color(255, 255, 255));
        lblMesa.setText("Mesa n");

        pnlEstado.setBackground(new java.awt.Color(80, 205, 137));
        pnlEstado.setRoundBottomLeft(15);
        pnlEstado.setRoundBottomRight(15);
        pnlEstado.setRoundTopLeft(15);
        pnlEstado.setRoundTopRight(15);

        lblEstado.setFont(new Font("Poppins", Font.PLAIN, 16));
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("Abierta");

        javax.swing.GroupLayout pnlEstadoLayout = new javax.swing.GroupLayout(pnlEstado);
        pnlEstado.setLayout(pnlEstadoLayout);
        pnlEstadoLayout.setHorizontalGroup(
                pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlEstadoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addContainerGap()));
        pnlEstadoLayout.setVerticalGroup(
                pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlEstadoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        lblFolio.setFont(new Font("Poppins", Font.PLAIN, 16));
        lblFolio.setForeground(new java.awt.Color(200, 200, 200));
        lblFolio.setText("Folio: OB-YYYYMMDD-XXX");

        lblFecha.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblFecha.setForeground(new java.awt.Color(200, 200, 200));
        lblFecha.setText("Fecha");

        lblHora.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblHora.setForeground(new java.awt.Color(200, 200, 200));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHora.setText("Hora");

        btnVerComanda.setBackground(new java.awt.Color(217, 217, 217));
        btnVerComanda.setForeground(new java.awt.Color(0, 0, 0));
        btnVerComanda.setRoundBottomLeft(20);
        btnVerComanda.setRoundBottomRight(20);
        btnVerComanda.setRoundTopLeft(20);
        btnVerComanda.setRoundTopRight(20);

        lblHora1.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblHora1.setForeground(new java.awt.Color(0, 0, 0));
        lblHora1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora1.setText("Ver Comanda");

        javax.swing.GroupLayout btnVerComandaLayout = new javax.swing.GroupLayout(btnVerComanda);
        btnVerComanda.setLayout(btnVerComandaLayout);
        btnVerComandaLayout.setHorizontalGroup(
                btnVerComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(btnVerComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                        btnVerComandaLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lblHora1, javax.swing.GroupLayout.DEFAULT_SIZE, 293,
                                                        Short.MAX_VALUE)
                                                .addContainerGap())));
        btnVerComandaLayout.setVerticalGroup(
                btnVerComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(btnVerComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(btnVerComandaLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lblHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(10, Short.MAX_VALUE))));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
                roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout
                                .createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(roundedPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnVerComanda, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                roundedPanel1Layout.createSequentialGroup()
                                                        .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblFolio, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addComponent(lblMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 136,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49,
                                                        Short.MAX_VALUE)
                                                .addComponent(pnlEstado, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)));
        roundedPanel1Layout.setVerticalGroup(
                roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(roundedPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pnlEstado, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(roundedPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnVerComanda, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(21, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel btnVerComanda;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHora1;
    private javax.swing.JLabel lblMesa;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel pnlEstado;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
