/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.sistemarestaurantepresentacion.paneles;

import itson.sistemarestaurantedominio.Ingrediente;
import itson.sistemarestaurantedominio.dtos.IngredienteDTO;
import java.awt.Font;

/**
 *
 * @author PC
 */
public class PnlIngrediente extends javax.swing.JPanel {
    
    private PnlBusquedaIngrediente parent;
    private IngredienteDTO ingrediente;

    /**
     * Constructor que inicializa sus atributos al valor de sus parametros
     *
     * @param parent Clase padre
     * @param ingrediente Ingrediente a mostrar
     */
    public PnlIngrediente(PnlBusquedaIngrediente parent, IngredienteDTO ingrediente) {
        this.parent = parent;
        this.ingrediente = ingrediente;
        btnModificarStock.setVisible(true);
        initComponents();
        cargarIngredientes();
    }

    /**
     * Constructor que inicializa el ingrediente a mostrar al valor de sus
     * parametros
     *
     * @param ingrediente Ingrediente a mostrar
     */
    public PnlIngrediente(IngredienteDTO ingrediente) {
        this.ingrediente = ingrediente;
        btnModificarStock.setVisible(false);
        initComponents();
        cargarIngredientes();
    }

    /**
     * Metodo que llena la informacion del ingrediente
     */
    private void cargarIngredientes() {
        String nombreProducto = ingrediente.getNombre();
        this.txtIngrediente.setText(nombreProducto);
        this.txtUnidadMedida.setText(ingrediente.getUnidadMedida().toString());
        this.txtStock.setText(ingrediente.getStock().toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        lblIngrediente = new javax.swing.JLabel();
        lblUnidadMedida = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        btnModificarStock = new javax.swing.JButton();
        txtIngrediente = new javax.swing.JLabel();
        txtUnidadMedida = new javax.swing.JLabel();
        txtStock = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 150));

        roundedPanel1.setBackground(new java.awt.Color(94, 94, 94));
        roundedPanel1.setMaximumSize(new java.awt.Dimension(1000, 150));
        roundedPanel1.setRoundBottomLeft(40);
        roundedPanel1.setRoundBottomRight(40);
        roundedPanel1.setRoundTopLeft(40);
        roundedPanel1.setRoundTopRight(40);

        lblIngrediente.setFont(new Font("Poppins", Font.BOLD, 18));
        lblIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente.setText("Ingrediente: ");

        lblUnidadMedida.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblUnidadMedida.setForeground(new java.awt.Color(255, 255, 255));
        lblUnidadMedida.setText("Unidad de medida:");

        lblStock.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblStock.setForeground(new java.awt.Color(255, 255, 255));
        lblStock.setText("Cantidad en Stock:");

        btnModificarStock.setBackground(new java.awt.Color(217, 217, 217));
        btnModificarStock.setFont(new Font("Poppins", Font.PLAIN, 16));
        btnModificarStock.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarStock.setText("Modificar Stock");
        btnModificarStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarStockActionPerformed(evt);
            }
        });

        txtIngrediente.setFont(new Font("Poppins", Font.BOLD, 18));
        txtIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        txtIngrediente.setText("Ingrediente");

        txtUnidadMedida.setFont(new Font("Poppins", Font.PLAIN, 18));
        txtUnidadMedida.setForeground(new java.awt.Color(255, 255, 255));
        txtUnidadMedida.setText("Unidad de medida");

        txtStock.setFont(new Font("Poppins", Font.PLAIN, 18));
        txtStock.setForeground(new java.awt.Color(255, 255, 255));
        txtStock.setText("Cantidad Stock");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblIngrediente)
                .addGap(15, 15, 15)
                .addComponent(txtIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lblUnidadMedida)
                .addGap(15, 15, 15)
                .addComponent(txtUnidadMedida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(lblStock)
                        .addGap(18, 18, 18)
                        .addComponent(txtStock)))
                .addGap(50, 50, 50))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnModificarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarStock;
    private javax.swing.JLabel lblIngrediente;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblUnidadMedida;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel roundedPanel1;
    private javax.swing.JLabel txtIngrediente;
    private javax.swing.JLabel txtStock;
    private javax.swing.JLabel txtUnidadMedida;
    // End of variables declaration//GEN-END:variables
}
