/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.sistemarestaurantepresentacion.paneles;

import java.awt.Font;

/**
 *
 * @author PC
 */
public class PnlIngrediente extends javax.swing.JPanel {

    /**
     * Creates new form PnlIngrediente
     */
    public PnlIngrediente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        lblIngrediente = new javax.swing.JLabel();
        lblUnidadMedida = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 150));

        roundedPanel1.setBackground(new java.awt.Color(94, 94, 94));
        roundedPanel1.setMaximumSize(new java.awt.Dimension(1000, 150));
        roundedPanel1.setRoundBottomLeft(40);
        roundedPanel1.setRoundBottomRight(40);
        roundedPanel1.setRoundTopLeft(40);
        roundedPanel1.setRoundTopRight(40);
        roundedPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel1MouseClicked(evt);
            }
        });

        lblIngrediente.setFont(new Font("Poppins", Font.BOLD, 18));
        lblIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        lblIngrediente.setText("Ingrediente: ");

        lblUnidadMedida.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblUnidadMedida.setForeground(new java.awt.Color(255, 255, 255));
        lblUnidadMedida.setText("Unidad de medida:");

        lblStock.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblStock.setForeground(new java.awt.Color(255, 255, 255));
        lblStock.setText("Cantidad en Stock:");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lblUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundedPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel1MouseClicked
//        if(parent != null){
//            if(parent.isSelectionMode()){
//                parent.setClienteSeleccionado(this.cliente);
//
//                //Cerrar el modal
//                ModalClientes modal = parent.getModalClientes();
//                if(modal != null){
//                    modal.dispose();
//                }
//            }
//        }
    }//GEN-LAST:event_roundedPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIngrediente;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblUnidadMedida;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
