package itson.sistemarestaurantepresentacion.paneles;

import java.awt.Font;

import itson.sistemarestaurantedominio.dtos.ProductoDTO;
import itson.sistemarestaurantepresentacion.modales.ModalProductos;

/**
 *
 * @author pc
 */
public class PnlProducto extends javax.swing.JPanel {

    private ProductoDTO producto;
    private PnlBusquedaProducto parent;
    /**
     * Creates new form PnlProducto
     */
    public PnlProducto(PnlBusquedaProducto parent, ProductoDTO producto) {
        this.parent = parent;
        this.producto = producto;
        initComponents();
        cargarProducto();
    }

    private void cargarProducto(){
        this.lblNombre.setText(producto.getNombre());
        this.lblCategoria.setText("Categoría: " + producto.getTipoProducto().toString());
        this.lblPrecio.setText("Precio: $" + producto.getPrecio().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        lblNombre = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 31, 31));

        roundedPanel1.setBackground(new java.awt.Color(40, 40, 40));
        roundedPanel1.setRoundBottomLeft(45);
        roundedPanel1.setRoundBottomRight(45);
        roundedPanel1.setRoundTopLeft(45);
        roundedPanel1.setRoundTopRight(45);
        roundedPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel1MouseClicked(evt);
            }
        });

        lblNombre.setFont(new Font("Poppins", Font.BOLD, 20));
        lblNombre.setText("Nombre Producto");

        lblCategoria.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblCategoria.setText("Categoría: ...");

        lblPrecio.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblPrecio.setText("Precio: $...");

        jButton1.setFont(new Font("Poppins", Font.PLAIN, 18));
        jButton1.setText("Ver Ingredientes");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundedPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel1MouseClicked
        setProducto();
        cerrarModal();
    }//GEN-LAST:event_roundedPanel1MouseClicked

    /**
     * Metodo para setear el producto seleccionado al panel de busqueda el producto seleccionado
     */
    private void setProducto(){
        if(parent.isSelectionMode()){
            parent.setProductoSeleccionado(producto);
        } 
    }

    private void cerrarModal(){
        if(parent.isSelectionMode()){
            ModalProductos modalProductos = parent.getModal();
            modalProductos.cerrarModal();
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
