package itson.sistemarestaurantepresentacion.paneles;

import java.awt.Font;

import itson.sistemarestaurantedominio.dtos.ProductoDTO;
import itson.sistemarestaurantepresentacion.control.ControlFlujo;
import itson.sistemarestaurantepresentacion.modales.ModalProductos;
import itson.sistemarestaurantepresentacion.modales.ModalVerIngredientes;
import java.awt.Cursor;

/**
 * Clase que representa un panel de producto en la interfaz de usuario. Este
 * panel muestra la información de un producto y permite ver sus ingredientes.
 *
 * @author pc
 */
public class PnlProducto extends javax.swing.JPanel {

    private ProductoDTO producto;
    private PnlBusquedaProducto parent;

    /**
     * Constructor que inicializa el panel
     *
     * @param parent Clase padre
     * @param producto Objeto producto
     */
    public PnlProducto(PnlBusquedaProducto parent, ProductoDTO producto) {
        this.parent = parent;
        this.producto = producto;
        initComponents();
        cargarProducto();
        if (parent.isSelectionMode()) {
            this.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }

    /**
     * Metodo que llena la informacion del producto
     */
    private void cargarProducto() {
        this.lblNombre.setText(producto.getNombre());
        this.lblCategoria.setText("Categoría: " + producto.getTipoProducto().toString());
        this.lblPrecio.setText("Precio: $" + producto.getPrecio().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        lblNombre = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnVerIngredientes = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 31, 31));
        setMaximumSize(new java.awt.Dimension(350, 238));

        roundedPanel1.setBackground(new java.awt.Color(40, 40, 40));
        roundedPanel1.setMaximumSize(new java.awt.Dimension(350, 238));
        roundedPanel1.setRoundBottomLeft(45);
        roundedPanel1.setRoundBottomRight(45);
        roundedPanel1.setRoundTopLeft(45);
        roundedPanel1.setRoundTopRight(45);
        roundedPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel1MouseClicked(evt);
            }
        });

        lblNombre.setFont(new Font("Poppins", Font.BOLD, 20));
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre Producto");

        lblCategoria.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Categoría: ...");

        lblPrecio.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio.setText("Precio: $...");

        btnVerIngredientes.setBackground(new java.awt.Color(94, 94, 94));
        btnVerIngredientes.setFont(new Font("Poppins", Font.PLAIN, 18));
        btnVerIngredientes.setForeground(new java.awt.Color(255, 255, 255));
        btnVerIngredientes.setText("Ver Ingredientes");
        btnVerIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerIngredientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnVerIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundedPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel1MouseClicked
        setProducto();
        cerrarModal();
    }//GEN-LAST:event_roundedPanel1MouseClicked

    private void btnVerIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerIngredientesActionPerformed
        if (parent.isSelectionMode()) {
            ModalVerIngredientes modal = new ModalVerIngredientes(null, true);
            modal.setProducto(this.producto);
            modal.setLocationRelativeTo(null);
            modal.setVisible(true);
        } else {
            ControlFlujo.mostrarPnlIngredientesProducto(this.producto);
        }
    }//GEN-LAST:event_btnVerIngredientesActionPerformed

    /**
     * Metodo para setear el producto seleccionado al panel de busqueda el
     * producto seleccionado
     */
    private void setProducto() {
        if (parent.isSelectionMode()) {
            parent.setProductoSeleccionado(producto);
        }
    }

    /**
     * Metodo para cerrar el modal de productos
     */
    private void cerrarModal() {
        if (parent.isSelectionMode()) {
            ModalProductos modalProductos = parent.getModal();
            modalProductos.cerrarModal();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerIngredientes;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
