package itson.sistemarestaurantepresentacion.pantallas;

import itson.sistemarestaurantepresentacion.recursos.RoundedPanel;
import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class FramePrincipal extends javax.swing.JFrame {

    private int currentSection = 0;
    private final int SECCION_INICIO = 0;
    private final int SECCION_COMANDAS = 1;
    private final int SECCION_PRODUCTOS = 2;
    private final int SECCION_INGREDIENTES = 3;
    private final int SECCION_CLIENTES = 4;
    private final int SECCION_MESAS = 5;
    private final int SECCION_REPORTES = 6;
    
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        panelNavegacion = new javax.swing.JPanel();
        pnlInicio = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        btnInicio = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        pnlComandas = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        btnComandas = new javax.swing.JLabel();
        lblComandas = new javax.swing.JLabel();
        pnlMenu = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        btnMenu = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        pnlIngredientes = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        btnIngredientes = new javax.swing.JLabel();
        lblIngredientes = new javax.swing.JLabel();
        pnlClientes = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        btnClientes = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        pnlMesas = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        btnMesas = new javax.swing.JLabel();
        lblMesas = new javax.swing.JLabel();
        pnlReportes = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        btnReportes = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Restaurante Genérico");
        setBackground(new java.awt.Color(37, 40, 54));

        panelNavegacion.setBackground(new java.awt.Color(31, 29, 43));
        panelNavegacion.setPreferredSize(new java.awt.Dimension(200, 146));

        pnlInicio.setBackground(new java.awt.Color(80, 205, 137));
        pnlInicio.setRoundBottomLeft(17);
        pnlInicio.setRoundBottomRight(17);
        pnlInicio.setRoundTopLeft(17);
        pnlInicio.setRoundTopRight(17);

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton inicio.png"))); // NOI18N
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });

        lblInicio.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("Inicio");
        lblInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInicioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlComandas.setBackground(new java.awt.Color(31, 29, 43));
        pnlComandas.setRoundBottomLeft(17);
        pnlComandas.setRoundBottomRight(17);
        pnlComandas.setRoundTopLeft(17);
        pnlComandas.setRoundTopRight(17);

        btnComandas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton comandas.png"))); // NOI18N
        btnComandas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComandas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComandasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComandasMouseExited(evt);
            }
        });

        lblComandas.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblComandas.setForeground(new java.awt.Color(255, 255, 255));
        lblComandas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComandas.setText("Comandas");
        lblComandas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblComandas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblComandasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblComandasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlComandasLayout = new javax.swing.GroupLayout(pnlComandas);
        pnlComandas.setLayout(pnlComandasLayout);
        pnlComandasLayout.setHorizontalGroup(
            pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComandasLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComandasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        pnlComandasLayout.setVerticalGroup(
            pnlComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComandasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.setBackground(new java.awt.Color(31, 29, 43));
        pnlMenu.setRoundBottomLeft(17);
        pnlMenu.setRoundBottomRight(17);
        pnlMenu.setRoundTopLeft(17);
        pnlMenu.setRoundTopRight(17);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton menu.png"))); // NOI18N
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });

        lblMenu.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menú");
        lblMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlIngredientes.setBackground(new java.awt.Color(31, 29, 43));
        pnlIngredientes.setRoundBottomLeft(17);
        pnlIngredientes.setRoundBottomRight(17);
        pnlIngredientes.setRoundTopLeft(17);
        pnlIngredientes.setRoundTopRight(17);

        btnIngredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton ingredientes.png"))); // NOI18N
        btnIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngredientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngredientesMouseExited(evt);
            }
        });

        lblIngredientes.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblIngredientes.setForeground(new java.awt.Color(255, 255, 255));
        lblIngredientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngredientes.setText("Ingredientes");
        lblIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIngredientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIngredientesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlIngredientesLayout = new javax.swing.GroupLayout(pnlIngredientes);
        pnlIngredientes.setLayout(pnlIngredientesLayout);
        pnlIngredientesLayout.setHorizontalGroup(
            pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngredientesLayout.createSequentialGroup()
                .addGroup(pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngredientesLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlIngredientesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIngredientesLayout.setVerticalGroup(
            pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngredientesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlClientes.setBackground(new java.awt.Color(31, 29, 43));
        pnlClientes.setRoundBottomLeft(17);
        pnlClientes.setRoundBottomRight(17);
        pnlClientes.setRoundTopLeft(17);
        pnlClientes.setRoundTopRight(17);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton clientes.png"))); // NOI18N
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });

        lblClientes.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClientes.setText("Clientes");
        lblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClientesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMesas.setBackground(new java.awt.Color(31, 29, 43));
        pnlMesas.setRoundBottomLeft(17);
        pnlMesas.setRoundBottomRight(17);
        pnlMesas.setRoundTopLeft(17);
        pnlMesas.setRoundTopRight(17);

        btnMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton mesas.png"))); // NOI18N
        btnMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMesasMouseExited(evt);
            }
        });

        lblMesas.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblMesas.setForeground(new java.awt.Color(255, 255, 255));
        lblMesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesas.setText("Mesas");
        lblMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMesasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMesasLayout = new javax.swing.GroupLayout(pnlMesas);
        pnlMesas.setLayout(pnlMesasLayout);
        pnlMesasLayout.setHorizontalGroup(
            pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesasLayout.createSequentialGroup()
                .addGroup(pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMesasLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMesasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlMesasLayout.setVerticalGroup(
            pnlMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlReportes.setBackground(new java.awt.Color(31, 29, 43));
        pnlReportes.setRoundBottomLeft(17);
        pnlReportes.setRoundBottomRight(17);
        pnlReportes.setRoundTopLeft(17);
        pnlReportes.setRoundTopRight(17);

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton reportes.png"))); // NOI18N
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
        });

        lblReportes.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblReportes.setForeground(new java.awt.Color(255, 255, 255));
        lblReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportes.setText("Reportes");
        lblReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReportesLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlReportesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelNavegacionLayout = new javax.swing.GroupLayout(panelNavegacion);
        panelNavegacion.setLayout(panelNavegacionLayout);
        panelNavegacionLayout.setHorizontalGroup(
            panelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavegacionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlComandas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addGroup(panelNavegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelNavegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelNavegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNavegacionLayout.setVerticalGroup(
            panelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavegacionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pnlComandas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pnlIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pnlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pnlMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pnlReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pnlPrincipal.setBackground(new java.awt.Color(37, 40, 54));
        pnlPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlFrameLayout = new javax.swing.GroupLayout(pnlFrame);
        pnlFrame.setLayout(pnlFrameLayout);
        pnlFrameLayout.setHorizontalGroup(
            pnlFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFrameLayout.createSequentialGroup()
                .addComponent(panelNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE))
        );
        pnlFrameLayout.setVerticalGroup(
            pnlFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFrameLayout.createSequentialGroup()
                .addComponent(panelNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseEntered
        if(currentSection != SECCION_INICIO){
            subrayar(lblInicio);
        }
    }//GEN-LAST:event_lblInicioMouseEntered

    private void lblInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseExited
        if(currentSection != SECCION_INICIO){
            dessubrayar(lblInicio);
        }
    }//GEN-LAST:event_lblInicioMouseExited

    private void btnComandasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComandasMouseEntered
        if(currentSection != SECCION_COMANDAS){
            colorearPanelHover(pnlComandas);
        }
    }//GEN-LAST:event_btnComandasMouseEntered

    private void btnComandasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComandasMouseExited
        if(currentSection!= SECCION_COMANDAS){
            descolorearPanelHover(pnlComandas);
        }
    }//GEN-LAST:event_btnComandasMouseExited

    private void lblComandasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComandasMouseEntered
        if(currentSection != SECCION_COMANDAS){
            subrayar(lblComandas);
        }
    }//GEN-LAST:event_lblComandasMouseEntered

    private void lblComandasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComandasMouseExited
        if(currentSection != SECCION_COMANDAS){
            dessubrayar(lblComandas);
        }
    }//GEN-LAST:event_lblComandasMouseExited

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        if(currentSection != SECCION_INICIO){
            colorearPanelHover(pnlInicio);
        }
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        if(currentSection != SECCION_INICIO){
            descolorearPanelHover(pnlInicio);
        }
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        if(currentSection != SECCION_PRODUCTOS){
            colorearPanelHover(pnlMenu);
        }
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        if(currentSection != SECCION_PRODUCTOS){
            descolorearPanelHover(pnlMenu);
        }
    }//GEN-LAST:event_btnMenuMouseExited

    private void lblMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseEntered
        if(currentSection != SECCION_PRODUCTOS){
            subrayar(lblMenu);
        }
    }//GEN-LAST:event_lblMenuMouseEntered

    private void lblMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseExited
        if(currentSection != SECCION_PRODUCTOS){
            dessubrayar(lblMenu);
        }
    }//GEN-LAST:event_lblMenuMouseExited

    private void btnIngredientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngredientesMouseEntered
        if(currentSection != SECCION_INGREDIENTES){
            colorearPanelHover(pnlIngredientes);
        }
    }//GEN-LAST:event_btnIngredientesMouseEntered

    private void btnIngredientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngredientesMouseExited
        if(currentSection != SECCION_INGREDIENTES){
            descolorearPanelHover(pnlIngredientes);
        }
    }//GEN-LAST:event_btnIngredientesMouseExited

    private void lblIngredientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIngredientesMouseEntered
        if(currentSection != SECCION_INGREDIENTES){
            subrayar(lblIngredientes);
        }
    }//GEN-LAST:event_lblIngredientesMouseEntered

    private void lblIngredientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIngredientesMouseExited
        if(currentSection != SECCION_INGREDIENTES){
            dessubrayar(lblIngredientes);
        }
    }//GEN-LAST:event_lblIngredientesMouseExited

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        if(currentSection != SECCION_CLIENTES){
            colorearPanelHover(pnlClientes);
        }
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        if(currentSection != SECCION_CLIENTES){
            descolorearPanelHover(pnlClientes);
        }
    }//GEN-LAST:event_btnClientesMouseExited

    private void lblClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseEntered
        if(currentSection != SECCION_CLIENTES){
            subrayar(lblClientes);
        }
    }//GEN-LAST:event_lblClientesMouseEntered

    private void lblClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseExited
        if(currentSection != SECCION_CLIENTES){
            dessubrayar(lblClientes);
        }
    }//GEN-LAST:event_lblClientesMouseExited

    private void btnMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesasMouseEntered
        if(currentSection != SECCION_MESAS){
            colorearPanelHover(pnlMesas);
        }
    }//GEN-LAST:event_btnMesasMouseEntered

    private void btnMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesasMouseExited
        if(currentSection != SECCION_MESAS){
            descolorearPanelHover(pnlMesas);
        }
    }//GEN-LAST:event_btnMesasMouseExited

    private void lblMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMesasMouseEntered
        if(currentSection != SECCION_MESAS){
            subrayar(lblMesas);
        }
    }//GEN-LAST:event_lblMesasMouseEntered

    private void lblMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMesasMouseExited
        if(currentSection != SECCION_MESAS){
            dessubrayar(lblMesas);
        }
    }//GEN-LAST:event_lblMesasMouseExited

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        if(currentSection != SECCION_REPORTES){
            colorearPanelHover(pnlReportes);
        }
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        if(currentSection != SECCION_REPORTES){
            descolorearPanelHover(pnlReportes);
        }
    }//GEN-LAST:event_btnReportesMouseExited

    private void lblReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseEntered
        if(currentSection != SECCION_REPORTES){
            subrayar(lblReportes);
        }
    }//GEN-LAST:event_lblReportesMouseEntered

    private void lblReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseExited
        if(currentSection != SECCION_REPORTES){
            dessubrayar(lblReportes);
        }
    }//GEN-LAST:event_lblReportesMouseExited

    /**
     * Metodo que cambia las propiedades de la fuente para que se muestre subrayada
     * @param label etiqueta a subrayar
     */
    private void subrayar(JLabel label){
        Font font = label.getFont();
        Map subrayado = font.getAttributes();
        subrayado.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        label.setFont(font.deriveFont(subrayado));
    }
    
    /**
     * Metodo que devuelve a su estado original una fuente
     * @param label etiqueta a devolver.
     */
    private void dessubrayar(JLabel label){
        Font font = label.getFont();
        String name = font.getName();
        int style = font.getStyle();
        int size = font.getSize();
        Font nuevaFont = new Font(name, style, size);
        label.setFont(nuevaFont);
    }
    
    /**
     * Metodo que colorea el fondo de un panel al momento de pasar el mouse sobre un boton
     * @param panel Panel a colorear
     */
    private void colorearPanelHover(RoundedPanel panel){
        panel.setBackground(new Color(51,51,51));
    }
    
    /**
     * Metodo que devuelve el fondo de un panel al momento de quitar el mouse sobre un boton
     * @param panel Panel a descolorear
     */
    private void descolorearPanelHover(RoundedPanel panel){
        panel.setBackground(new Color(31,29,43));
    }

    public JPanel getPnlPrincipal() {
        return pnlPrincipal;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClientes;
    private javax.swing.JLabel btnComandas;
    private javax.swing.JLabel btnIngredientes;
    private javax.swing.JLabel btnInicio;
    private javax.swing.JLabel btnMenu;
    private javax.swing.JLabel btnMesas;
    private javax.swing.JLabel btnReportes;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblComandas;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMesas;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JPanel panelNavegacion;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel pnlClientes;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel pnlComandas;
    private javax.swing.JPanel pnlFrame;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel pnlIngredientes;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel pnlInicio;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel pnlMenu;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel pnlMesas;
    private javax.swing.JPanel pnlPrincipal;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel pnlReportes;
    // End of variables declaration//GEN-END:variables
}
