
package itson.sistemarestaurantepresentacion.pantallas;

import itson.sistemarestaurantedominio.dtos.IngredienteDTO;
import itson.sistemarestaurantedominio.dtos.IngredienteProductoDTO;
import itson.sistemarestaurantedominio.dtos.NuevoProductoDTO;
import itson.sistemarestaurantedominio.enumeradores.TipoProducto;
import itson.sistemarestaurantenegocio.excepciones.NegocioException;
import itson.sistemarestaurantenegocio.factory.ObjetosNegocioFactory;
import itson.sistemarestaurantenegocio.interfaces.IProductosBO;
import itson.sistemarestaurantepresentacion.control.ControlFlujo;
import itson.sistemarestaurantepresentacion.modales.ModalIngredientes;
import itson.sistemarestaurantepresentacion.paneles.PnlIngredienteProducto;

import java.awt.Font;
import java.math.BigDecimal;
import java.util.LinkedList;
import java.util.List;

import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 * Clase que representa un panel para agregar un nuevo producto en la
 * interfaz de usuario. Este panel permite al usuario ingresar el nombre, precio
 * y tipo de producto,
 * 
 * @author pc
 */
public class PnlAgregarProducto extends javax.swing.JPanel {

        List<PnlIngredienteProducto> ingredientes = new LinkedList<>();

        /**
         * Creates new form PnlAgregarProducto
         */
        public PnlAgregarProducto() {
                initComponents();
                cargarTiposProducto();
        }

        /**
         * Metodo que carga los tipos de producto al comboBox
         */
        private void cargarTiposProducto() {
                TipoProducto[] tipos = TipoProducto.values();
                comboBoxTipo.removeAllItems();
                comboBoxTipo.addItem("Selecciona un tipo");
                comboBoxTipo.setSelectedIndex(0);
                // Agregar los tipos de producto al comboBox
                for (TipoProducto tipo : tipos) {
                        comboBoxTipo.addItem(
                                        tipo.toString().substring(0, 1).toUpperCase()
                                                        + tipo.toString().substring(1).toLowerCase());
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pnlPrincipal = new javax.swing.JPanel();
                lblTitulo = new javax.swing.JLabel();
                btnVolver = new javax.swing.JButton();
                pnlComanda = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
                lblNombre = new javax.swing.JLabel();
                btnBuscarIngredientes = new javax.swing.JButton();
                lblCliente = new javax.swing.JLabel();
                txtCliente = new javax.swing.JLabel();
                scrollPnlIngredientesProducto = new javax.swing.JScrollPane();
                pnlIngredientesProducto = new javax.swing.JPanel();
                txtNombre = new javax.swing.JTextField();
                txtPrecio = new javax.swing.JTextField();
                lblTipo = new javax.swing.JLabel();
                comboBoxTipo = new javax.swing.JComboBox<>();
                btnAgregar = new javax.swing.JButton();

                pnlPrincipal.setBackground(new java.awt.Color(37, 40, 54));

                lblTitulo.setFont(new Font("Poppins", Font.BOLD, 36));
                lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
                lblTitulo.setText("Agregar Nuevo Producto");

                btnVolver.setBackground(new java.awt.Color(94, 94, 94));
                btnVolver.setFont(new Font("Poppins", Font.PLAIN, 18));
                btnVolver.setForeground(new java.awt.Color(255, 255, 255));
                btnVolver.setText("Volver");
                btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnVolver.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnVolverActionPerformed(evt);
                        }
                });

                pnlComanda.setBackground(new java.awt.Color(31, 31, 31));
                pnlComanda.setRoundBottomLeft(50);
                pnlComanda.setRoundBottomRight(50);
                pnlComanda.setRoundTopLeft(50);
                pnlComanda.setRoundTopRight(50);

                lblNombre.setFont(new Font("Poppins", Font.PLAIN, 18));
                lblNombre.setForeground(new java.awt.Color(255, 255, 255));
                lblNombre.setText("Nombre del producto:");

                btnBuscarIngredientes.setBackground(new java.awt.Color(217, 217, 217));
                btnBuscarIngredientes.setFont(new Font("Poppins", Font.PLAIN, 16));
                btnBuscarIngredientes.setForeground(new java.awt.Color(0, 0, 0));
                btnBuscarIngredientes.setText("Buscar Ingredientes");
                btnBuscarIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnBuscarIngredientes.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBuscarIngredientesActionPerformed(evt);
                        }
                });

                lblCliente.setFont(new Font("Poppins", Font.PLAIN, 18));
                lblCliente.setForeground(new java.awt.Color(255, 255, 255));
                lblCliente.setText("Precio: ");

                txtCliente.setFont(new Font("Poppins", Font.PLAIN, 18));
                txtCliente.setForeground(new java.awt.Color(255, 255, 255));

                scrollPnlIngredientesProducto.setBorder(null);

                pnlIngredientesProducto.setBackground(new java.awt.Color(31, 31, 31));
                pnlIngredientesProducto
                                .setLayout(new javax.swing.BoxLayout(pnlIngredientesProducto,
                                                javax.swing.BoxLayout.Y_AXIS));
                scrollPnlIngredientesProducto.setViewportView(pnlIngredientesProducto);

                txtNombre.setBackground(new java.awt.Color(255, 255, 255));
                txtNombre.setFont(new Font("Poppins", Font.PLAIN, 18));
                txtNombre.setForeground(new java.awt.Color(0, 0, 0));

                txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
                txtPrecio.setFont(new Font("Poppins", Font.PLAIN, 18));
                txtPrecio.setForeground(new java.awt.Color(0, 0, 0));

                lblTipo.setFont(new Font("Poppins", Font.PLAIN, 18));
                lblTipo.setForeground(new java.awt.Color(255, 255, 255));
                lblTipo.setText("Tipo de Producto:");

                comboBoxTipo.setBackground(new java.awt.Color(255, 255, 255));
                comboBoxTipo.setFont(new Font("Poppins", Font.PLAIN, 18));
                comboBoxTipo.setForeground(new java.awt.Color(0, 0, 0));

                javax.swing.GroupLayout pnlComandaLayout = new javax.swing.GroupLayout(pnlComanda);
                pnlComanda.setLayout(pnlComandaLayout);
                pnlComandaLayout.setHorizontalGroup(
                                pnlComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlComandaLayout.createSequentialGroup()
                                                                .addGap(46, 46, 46)
                                                                .addGroup(pnlComandaLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(pnlComandaLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(scrollPnlIngredientesProducto,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                1020,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addContainerGap(46,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(pnlComandaLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(pnlComandaLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(pnlComandaLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lblNombre,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                178,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(txtNombre,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                328,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(28, 28, 28))
                                                                                                                .addGroup(pnlComandaLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lblTipo,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                178,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(comboBoxTipo,
                                                                                                                                                0,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGap(27, 27, 27)))
                                                                                                .addGroup(pnlComandaLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(pnlComandaLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lblCliente,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                70,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(txtPrecio,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                284,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(txtCliente,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addComponent(btnBuscarIngredientes,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addGap(107, 107,
                                                                                                                107)))));
                pnlComandaLayout.setVerticalGroup(
                                pnlComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlComandaLayout.createSequentialGroup()
                                                                .addGap(42, 42, 42)
                                                                .addGroup(
                                                                                pnlComandaLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(lblNombre,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                40,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(lblCliente,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                40,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(txtCliente,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                40,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(txtNombre,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                40,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(txtPrecio,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                40,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlComandaLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(lblTipo,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(comboBoxTipo)
                                                                                .addComponent(btnBuscarIngredientes,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                40,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(28, 28, 28)
                                                                .addComponent(scrollPnlIngredientesProducto,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                440,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(35, Short.MAX_VALUE)));

                btnAgregar.setBackground(new java.awt.Color(80, 205, 137));
                btnAgregar.setFont(new Font("Poppins", Font.PLAIN, 18));
                btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
                btnAgregar.setText("Agregar Producto");
                btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnAgregar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAgregarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
                pnlPrincipal.setLayout(pnlPrincipalLayout);
                pnlPrincipalLayout.setHorizontalGroup(
                                pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                                                .addGap(374, 374, 374)
                                                                .addComponent(btnAgregar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                492,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout
                                                                .createSequentialGroup()
                                                                .addGap(80, 80, 80)
                                                                .addComponent(lblTitulo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                429,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                285,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(btnVolver,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                350,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(96, 96, 96))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(pnlComanda,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(64, 64, 64)));
                pnlPrincipalLayout.setVerticalGroup(
                                pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                                                .addGap(58, 58, 58)
                                                                .addGroup(pnlPrincipalLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lblTitulo,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                54,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnVolver,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                50,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(46, 46, 46)
                                                                .addComponent(pnlComanda,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                27,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(btnAgregar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                50,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(52, 52, 52)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(pnlPrincipal,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        }// </editor-fold>//GEN-END:initComponents

        /**
         * Método que se ejecuta al hacer clic en el botón "Volver".
         * 
         * @param evt Evento de acción del botón
         */
        private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
                if (ingredientes.isEmpty()) {
                        ControlFlujo.mostrarPnlProductos();
                        return;
                }
                int confirmacion = JOptionPane.showConfirmDialog(this,
                                "¿Estás seguro de que deseas cancelar?", "Confirmar cancelación",
                                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (confirmacion == JOptionPane.YES_OPTION) {
                        ControlFlujo.mostrarPnlProductos();
                }
        }// GEN-LAST:event_btnCancelarActionPerformed

        /**
         * Método que se ejecuta al hacer clic en el botón "Agregar Producto".
         * Valida los campos de entrada y agrega el nuevo producto a la base de datos.
         * 
         * @param evt Evento de acción del botón
         */
        private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarActionPerformed
                try {
                        String nombre = txtNombre.getText();
                        String precio = txtPrecio.getText();
                        TipoProducto tipo = TipoProducto
                                        .valueOf(comboBoxTipo.getSelectedItem().toString().toUpperCase());
                        if (nombre.isEmpty() || precio.isEmpty() || tipo == null) {
                                throw new NegocioException("Por favor llene todos los campos");
                        }
                        BigDecimal precioDecimal = new BigDecimal(precio);
                        IProductosBO productosBO = ObjetosNegocioFactory.crearProductosBO();
                        if (ingredientes.isEmpty()) {
                                throw new NegocioException("Asegurese de agregar un ingrediente");
                        }
                        List<IngredienteProductoDTO> ingredientes = cargarRelaciones();
                        if (ingredientes == null) {
                                return;
                        }
                        NuevoProductoDTO nuevoProducto = new NuevoProductoDTO(nombre, precioDecimal, tipo,
                                        ingredientes);
                        productosBO.agregarProducto(nuevoProducto);
                        JOptionPane.showMessageDialog(this, "El producto se ha agregado correctamente.", "Éxito",
                                        JOptionPane.INFORMATION_MESSAGE);
                        ControlFlujo.mostrarPnlProductos();
                } catch (NegocioException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                } catch (IllegalArgumentException e) {
                        JOptionPane.showMessageDialog(this, "Seleccione un tipo valido", "Error", JOptionPane.ERROR_MESSAGE);

                }

        }// GEN-LAST:event_btnAgregarActionPerformed

        private void btnBuscarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {
                ModalIngredientes modal = new ModalIngredientes(null, true);
                IngredienteDTO ingrediente = modal.obtenerIngrediente();
                if (ingrediente != null) {
                        PnlIngredienteProducto pnlIngrediente = new PnlIngredienteProducto(ingrediente);
                        ingredientes.add(pnlIngrediente);
                        cargarPanelesIngredientes();
                }
        }

        /**
         * Método para cargar las relaciones de los ingredientes que pertenecen al
         * producto
         * 
         * @return List<IngredienteProductoDTO> lista de ingredientes
         * @throws NumberFormatException si la cantidad no es un número válido1
         */
        private List<IngredienteProductoDTO> cargarRelaciones() {
                List<IngredienteProductoDTO> ingredientesDTO = new LinkedList<>();
                try {
                        for (PnlIngredienteProducto ingrediente : ingredientes) {
                                Long id = ingrediente.getIngrediente().getId();
                                String strCantidad = ingrediente.getTxtCantidad().getText();
                                if (strCantidad.isEmpty()) {
                                        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.",
                                                        "Error",
                                                        JOptionPane.ERROR_MESSAGE);
                                        return null;
                                }
                                Integer cantidad = Integer.parseInt(strCantidad);
                                IngredienteProductoDTO ingredienteDTO = new IngredienteProductoDTO(id, cantidad);
                                ingredientesDTO.add(ingredienteDTO);
                        }
                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                                        return null;
                }

                return ingredientesDTO;
        }

        /**
         * Método para cargar los paneles de ingredientes en el panel
         * pnlIngredientesProducto.
         * Este método recorre la lista de ingredientes y agrega cada panel
         * PnlIngredienteProducto al panel pnlIngredientesProducto.
         */
        private void cargarPanelesIngredientes() {
                pnlIngredientesProducto.removeAll();
                for (PnlIngredienteProducto ingrediente : ingredientes) {
                        pnlIngredientesProducto.add(ingrediente);
                        pnlIngredientesProducto.add(Box.createVerticalStrut(15));
                }
                pnlIngredientesProducto.revalidate();
                pnlIngredientesProducto.repaint();
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAgregar;
        private javax.swing.JButton btnBuscarIngredientes;
        private javax.swing.JButton btnVolver;
        private javax.swing.JComboBox<String> comboBoxTipo;
        private javax.swing.JLabel lblCliente;
        private javax.swing.JLabel lblNombre;
        private javax.swing.JLabel lblTipo;
        private javax.swing.JLabel lblTitulo;
        private itson.sistemarestaurantepresentacion.recursos.RoundedPanel pnlComanda;
        private javax.swing.JPanel pnlIngredientesProducto;
        private javax.swing.JPanel pnlPrincipal;
        private javax.swing.JScrollPane scrollPnlIngredientesProducto;
        private javax.swing.JLabel txtCliente;
        private javax.swing.JTextField txtNombre;
        private javax.swing.JTextField txtPrecio;
        // End of variables declaration//GEN-END:variables
}
