package itson.sistemarestaurantepresentacion.pantallas;

import java.awt.Font;
import java.util.List;

import javax.swing.JOptionPane;

import itson.sistemarestaurantedominio.dtos.IngredienteProductoDTO;
import itson.sistemarestaurantedominio.dtos.ProductoDTO;
import itson.sistemarestaurantenegocio.excepciones.NegocioException;
import itson.sistemarestaurantenegocio.factory.ObjetosNegocioFactory;
import itson.sistemarestaurantenegocio.interfaces.IIngredientesProductoBO;
import itson.sistemarestaurantepresentacion.control.ControlFlujo;
import itson.sistemarestaurantepresentacion.modales.ModalVerIngredientes;
import itson.sistemarestaurantepresentacion.paneles.PnlIngredienteProductoGuardado;

/**
 * Clase que representa un panel de ingredientes de un producto en la interfaz de usuario.
 * Este panel muestra la información de un producto y sus ingredientes.
 * @author pc
 */
public class PnlIngredientesProducto extends javax.swing.JPanel {

    private ProductoDTO producto;
    private ModalVerIngredientes modal;
    
    /**
     * Creates new form PnlIngredientesProducto
     */
    public PnlIngredientesProducto(ProductoDTO producto) {
        this.producto = producto;
        initComponents();
        cargarProducto();
        cargarIngredientes();
    }
    
    /**
     * Crea un frm PnlIngredientesProducto, despues se setearía el producto
     */
    public PnlIngredientesProducto(){
        initComponents();
    }

    private void cargarProducto(){
        String nombreProducto = producto.getNombre();
        this.lblNombre.setText("Nombre del Producto: " + nombreProducto);
        this.lblPrecio.setText("Precio: $" + producto.getPrecio().toString());
        this.lblTipo.setText("Tipo de Producto: " + producto.getTipoProducto().toString().substring(0,1).toUpperCase() + producto.getTipoProducto().toString().substring(1));        
    }

    /**
     * Metodo que carga los ingredientes del producto
     */
    private void cargarIngredientes(){
        this.pnlIngredientesProducto.removeAll();
        IIngredientesProductoBO ingredientesProductosBO = ObjetosNegocioFactory.crearIngredientesProductoBO();
        try{
            List<IngredienteProductoDTO> ingredientes = ingredientesProductosBO.obtenerIngredientesProductoPorIdProducto(producto.getId());
            for(IngredienteProductoDTO ingrediente : ingredientes){
                PnlIngredienteProductoGuardado pnlIngrediente = new PnlIngredienteProductoGuardado(ingrediente);
                this.pnlIngredientesProducto.add(pnlIngrediente);
                this.pnlIngredientesProducto.add(javax.swing.Box.createVerticalStrut(15));
            }
        } catch(NegocioException ex){
            JOptionPane.showMessageDialog(this, "Error al cargar los ingredientes: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.pnlIngredientesProducto.revalidate();
        this.pnlIngredientesProducto.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        pnlComanda = new itson.sistemarestaurantepresentacion.recursos.RoundedPanel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        scrollPnlIngredientesProducto = new javax.swing.JScrollPane();
        pnlIngredientesProducto = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        lblIngredientes = new javax.swing.JLabel();

        pnlPrincipal.setBackground(new java.awt.Color(37, 40, 54));

        lblTitulo.setFont(new Font("Poppins", Font.BOLD, 36));
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Ingredientes del Producto");

        btnVolver.setBackground(new java.awt.Color(94, 94, 94));
        btnVolver.setFont(new Font("Poppins", Font.PLAIN, 18));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        pnlComanda.setBackground(new java.awt.Color(31, 31, 31));
        pnlComanda.setRoundBottomLeft(50);
        pnlComanda.setRoundBottomRight(50);
        pnlComanda.setRoundTopLeft(50);
        pnlComanda.setRoundTopRight(50);

        lblNombre.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre del producto:");

        lblPrecio.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio.setText("Precio: ");

        scrollPnlIngredientesProducto.setBorder(null);

        pnlIngredientesProducto.setBackground(new java.awt.Color(31, 31, 31));
        pnlIngredientesProducto.setLayout(new javax.swing.BoxLayout(pnlIngredientesProducto, javax.swing.BoxLayout.Y_AXIS));
        scrollPnlIngredientesProducto.setViewportView(pnlIngredientesProducto);

        lblTipo.setFont(new Font("Poppins", Font.PLAIN, 18));
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("Tipo de Producto:");

        lblIngredientes.setFont(new Font("Poppins", Font.BOLD, 18));
        lblIngredientes.setForeground(new java.awt.Color(255, 255, 255));
        lblIngredientes.setText("Ingredientes");

        javax.swing.GroupLayout pnlComandaLayout = new javax.swing.GroupLayout(pnlComanda);
        pnlComanda.setLayout(pnlComandaLayout);
        pnlComandaLayout.setHorizontalGroup(
            pnlComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComandaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComandaLayout.createSequentialGroup()
                        .addComponent(lblIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlComandaLayout.createSequentialGroup()
                        .addGroup(pnlComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPnlIngredientesProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlComandaLayout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        pnlComandaLayout.setVerticalGroup(
            pnlComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComandaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPnlIngredientesProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(pnlComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(pnlComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if(modal == null){
            ControlFlujo.mostrarPnlProductos();
        } else {
            modal.dispose();
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    public void setProducto(ProductoDTO producto){
        this.producto = producto;
        cargarProducto();
        cargarIngredientes();
    }
    
    public ProductoDTO getProducto(){
        return producto;
    }
    
    public void setModal(ModalVerIngredientes modal){
        this.modal = modal;
    }
    
    public ModalVerIngredientes isModal(){
        return modal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private itson.sistemarestaurantepresentacion.recursos.RoundedPanel pnlComanda;
    private javax.swing.JPanel pnlIngredientesProducto;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane scrollPnlIngredientesProducto;
    // End of variables declaration//GEN-END:variables
}
